### ISSUE TITLE
setUnleashContext() doesn't update useFlags() return value

### ISSUE THREAD

**Issue by robertjk** [Unleash/proxy-client-react#106]
### Describe the bug

When I run my React app and update Unleash context using `setUnleashContext()` (return value from `useUnleashContext()`) the flags returned by `useFlags()` aren't updated (not re-calculated in the new context, but preserving values from the old one). If I used `useFlag()` hook instead, the updates propagate immediately, and even `useFlags()` start to return proper values.

So it seems to me there is some synchronization problem between `setUnleashContext()` and `useFlags()`.

### Steps to reproduce the bug

1. Create feature toggle `TestToggle` with User ID strategy. Enable it for 1 user with ID `'userEnabled'`.
2. Create and run a simple component to test `setUnleashContext()`:
    ```
    function TestComponent() {
      const flags = useFlags().map(toggle => toggle.name);
      console.log('flags:', flags);

      const setUnleashContext = useUnleashContext();

      useEffect(() => {
          setUnleashContext({ userId: 'userEnabled' });
      }, []);

      useEffect(() => {
          const timeout = setTimeout(() => {
              setUnleashContext({ userId: 'userDisabled' });
              console.log('Unleash context modified');
          }, 5000);
          return () => clearTimeout(timeout);
      }, []);

      return null;
    }
    ```
3. The output in the console is:
    ```
    flags: ['TestToggle']
    Unleash context modified
    flags: ['TestToggle']  // This line actually doesn't show until I force a re-render
    ```

### Expected behavior

I'd expect the output in the console to be:

```
flags: ['TestToggle']
Unleash context modified
flags: []
```

#### useFlag() works fine

If instead of grabbing all flags using `useFlags()`:

```
const flags = useFlags.map(toggle => toggle.name);
```

I grab only this particular flag using `useFlag()`:

```
const flag = useFlag('TestToggle');
```

the result is correct (`false` after updating the context) and even `useFlags()` calls are updated and stop to return `TestToggle`. So it seems usage of `useFlag()` for this particular flag triggers re-calculation in new context, while usage of `useFlags()` does not.

#### Using client directly

Today I tried to achieve the same by using client directly (`useUnleashClient()`). The results were exactly the same - when getting all flags the results weren't up to date with the context, but when getting a single flag they did. So it seems to me the problem is within the underlying client, not the React wrapper here.

### Unleash version

Unleash 4.19.3

### Subscription type

Open source

### Hosting type

Self-hosted

### SDK information (language and version)

@unleash/proxy-client-react 3.5.0, unleash-proxy-client 2.4.0

**Comment by andreas-unleash** [comment]
Hi @robertjk , thanks for bringing this to our attention! I will let the team know and triage it and get back to you.

**Comment by robertjk** [comment]
@andreas-unleash Thanks. I will be waiting for further feedback then.

**Comment by Tymek** [comment]
New beta should be out tomorrow

**Comment by robertjk** [comment]
> New beta release should be out tomorrow

Great to hear that. Thanks!

**Comment by Tymek** [comment]
`3.5.2-beta.1`

**Comment by robertjk** [comment]
By the way I saw the fix is in this repository. While debugging this issue I tried using the client directly `useUnleashClient()` and the problem persisted the same. Doesn't that mean [unleash-proxy-client-js](https://github.com/unleash/unleash-proxy-client-js) needs a fix as well?

**Comment by Tymek** [comment]
I beg to differ 😅 
https://codesandbox.io/s/unleash-react-beta-yj20pi?file=/src/App.js

Are you sure everything is OK with your setup? Do you have `3.5.2-beta.1` installed? Can you provide an example?

**Comment by robertjk** [comment]
I meant the situation before this fix was released. It seemed to me `unleash-proxy-client-js` should suffer from the same issue, not only `@unleash/proxy-client-react`.

On Monday I'll test this new release of `@unleash/proxy-client-react` and will test using the client directly as well. If there is a problem, I'll come back here.

**Comment by Tymek** [comment]
React SDK depends on `unleash-proxy-client`, but it holds "local state" in the hook, and that was the issue.

**Comment by robertjk** [comment]
I tested `3.5.2-beta.1` version and it seems to me the issue is fixed only partially:
 - Indeed now after calling `setUnleashContext()` the flags returned by `useFlags()` are updated, but not immediately, only at the next refresh (With default `refreshInterval` value it will usually take up to 5 seconds for the flags result to be updated)
 - I would expect `setUnleashContext()` to have immediate effect, forcing re-fetching the flags and updating all `useFlag()` and `useFlags()` calls to return updated values

It seems to me the problem in the underlying code is not calling `fetchToggles()`. When I call this method in my code (even though it's marked as `private` 🙄) after calling `setUnleashContext()` the effect is immediate.

**Comment by Tymek** [comment]
I attempted to reproduce issues you have here https://codesandbox.io/s/unleash-react-beta-yj20pi?file=/src/App.js but I couldn't. 

The only thing I found is that if `refreshInterval` is `0` it stops working.

**Comment by robertjk** [comment]
Thanks for this update. Then let me continue debugging it. Maybe there is something wrong in my setup.

**Comment by robertjk** [comment]
Okay, after half day of debugging I eventually found the reason why it wasn't working. I did update `@unleash/proxy-client-react` but did not update `unleash-proxy-client` to 2.4.2. You can see in your demo that with `unleash-proxy-client@2.4.0` it doesn't work neither. So there were issues in both packages after all, as I mentioned before.

Anyway, everything seems to work fine now, which is the most important

**Comment by Tymek** [comment]
`3.5.2` is out now, as well as `unleash-proxy-client@2.4.3`
