### ISSUE TITLE
Updating context doesn't refresh toggles when refreshInterval is 0

### ISSUE THREAD

**Issue by Tymek** [Unleash/proxy-client-react#109]
### Describe the bug

If you configure `FlagProvider` with `refreshInterval: 0`, `useFlags` should still refresh when you update the context.

### Steps to reproduce the bug

1. https://codesandbox.io/s/unleash-react-beta-forked-h59few?file=/src/App.js
2. after changing text input value and submitting there is no request for new toggles

### SDK information (language and version)

React SDK - current beta

## Relevant discussion
https://github.com/Unleash/proxy-client-react/issues/106

**Comment by FredrikOseberg** [comment]
I think this needs to be fixed in unleash-proxy-client-js: 

https://github.com/Unleash/unleash-proxy-client-js/blob/main/src/index.ts#L249
