### ISSUE TITLE
State update in Context can cause hydration error #421

### ISSUE THREAD

**Issue by faessler** [Unleash/proxy-client-react#124]
### Describe the bug

If a project uses `react@18` with [lazy/Suspense](https://react.dev/reference/react/lazy) it can throw a hydration error and cause the website to fully rerender on the client (bad for CLS). This is because the [state inside FlagProvider](https://github.com/Unleash/proxy-client-react/blob/main/src/FlagProvider.tsx#L50-L60) gets updated. If we wrap the `setFlagsError`/`setFlagsReady` with [`startTransition`](https://react.dev/reference/react/startTransition) the error will be gone. 

**Error message:**
> This Suspense boundary received an update before it finished hydrating. This caused the boundary to switch to client rendering. The usual way to fix this is to wrap the original update in startTransition.

https://legacy.reactjs.org/docs/error-decoder.html/?invariant=421

_Side note: The error will only occur if the lazy loaded component is larger and slower during load. In our production project we only encountered the error when we throttled the network speed. Google SEO bots still picked the CLS up though._

### Steps to reproduce the bug

1. Go to https://y4r4q4-9000.csb.app/
2. Open the devtools > console
3. Look at hydration error in the console

- I've created a reproduction repository on codesandbox.io: https://codesandbox.io/p/sandbox/great-dawn-y4r4q4?file=%2Fsrc%2Fcomponents%2FMain.jsx%3A7%2C1-7%2C66
- A timeout was used with lazy to simulate a large component that needs longer to load
- Inside the reproduction repository is a modified version of `@unleash/proxy-client-react` package with `startTransition`
- You can run `yarn remove @unleash/proxy-client-react && yarn add ./@unleash/proxy-client-react && yarn clean && yarn build && yarn serve` to see the version with `startTransition` (error is gone in console 🧙)

### Expected behavior

No hydration error is shown.

### Screenshots

![image](https://github.com/Unleash/proxy-client-react/assets/7090566/185e4cba-3dda-452a-9b43-ed3a5fc671ef)

### Unleash version

3.6.0

### Subscription type

None

### Hosting type

Self-hosted

**Comment by faessler** [comment]
I created a PR with the changes to fix the error, hope it's helpful. Let me know if there are any questions! :)

**Comment by mfrachet** [comment]
Related issue in React itself: https://github.com/facebook/react/issues/24476 the suggested change would make sense according to https://github.com/facebook/react/issues/24476#issuecomment-1127800350
