### ISSUE TITLE
option to have useVariant update on payload.value change

### ISSUE THREAD

**Issue by deanohyeah** [Unleash/proxy-client-react#129]
### Describe the feature request

useVariant only updates on name or enabled changes.
It would be useful to update if the variant payload changes as well.
Or at least the option to opt into that behavior.

### Solution suggestions

add
```
        variantRef.current.payload?.value !== newVariant?.payload?.value
```
to 
https://github.com/Unleash/proxy-client-react/blob/main/src/useVariant.ts#L22

or add an options parameter to the hook that would conditionally do that.

**Comment by thomasheartman** [comment]
Hey! Thanks for the feature request 😄 And yeah, you make a good point; this looks like an oversight to me. I'll see what we can do 🙋🏼
