### ISSUE TITLE
Missing type declarations in version 4.0.0

### ISSUE THREAD

**Issue by doktor500** [Unleash/proxy-client-react#136]
### Describe the bug

<img width="1059" alt="Screenshot 2023-10-05 at 12 43 05" src="https://github.com/Unleash/proxy-client-react/assets/1174998/1c2424b7-0e55-4190-b446-416f76820764">

### Steps to reproduce the bug

When executing `npm install` it seems the IDE can not find the TypeScript type declarations after the latest release

### Expected behavior

The error on the IDE should go away

### Unleash version

4.0.0

### Subscription type

None

### Hosting type

None

**Comment by andreas-unleash** [comment]
Thanks for bringing this to our attention @doktor500 . We should have a fix out very shortly

**Comment by doktor500** [comment]
No worries, thanks for the quick fix
