### ISSUE TITLE
Named export 'IStorageProvider' not found

### ISSUE THREAD

**Issue by AdrienFromToulouse** [Unleash/proxy-client-react#138]
### Describe the bug

Hi, 

after upgrading @unleash/proxy-client-react from 3.6.0 to 4.0.1 we have this error at build time:

```
SyntaxError: Named export 'IStorageProvider' not found. The requested module 'unleash-proxy-client' is a CommonJS module, which may not support all module.exports as named exports.
```

Could it be related to the `dist` having a missing piece?

Cheers,

### Expected behavior

To import `import { useUnleashContext, FlagProvider } from '@unleash/proxy-client-react';` without error.

### Logs, error output, etc.

```bash
import { IStorageProvider as Y, InMemoryStorageProvider as j, LocalStorageProvider as D, UnleashClient as G } from "unleash-proxy-client";
         ^^^^^^^^^^^^^^^^
SyntaxError: Named export 'IStorageProvider' not found. The requested module 'unleash-proxy-client' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'unleash-proxy-client';
const { IStorageProvider: Y, InMemoryStorageProvider: j, LocalStorageProvider: D, UnleashClient: G } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:128:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:194:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15) {
```

### Unleash version

4.0.1

### Subscription type

Pro

### Hosting type

Hosted by Unleash

### SDK information (language and version)

typescript, react

**Comment by hqwlkj** [comment]
I also encountered the same problem.

![image](https://github.com/Unleash/proxy-client-react/assets/12181423/82d97bbc-8f9f-4092-bcf7-ff5443d4eced)

**Comment by Tymek** [comment]
@AdrienFromToulouse @hqwlkj can you please check `unleash-proxy-client@v3.0.0-beta.1`?

**Comment by AdrienFromToulouse** [comment]
not sure to understand sorry, to quote myself:
> after upgrading @unleash/proxy-client-react from 3.6.0 to 4.0.1 we have this error at build time:

So trying `v3.0.0-beta.1` might not be specially usefull.
We are using NextJs latest version if it can help you reproduce the issue.

**Comment by Tymek** [comment]
I'm trying to reproduce it. What's the version of Node this issue occurs on? Is it possible to reproduce it in Codesandbox or similar tool?

**Comment by Tymek** [comment]
Thanks! I managed to reproduce it on my end

**Comment by AdrienFromToulouse** [comment]
> Thanks! I managed to reproduce it on my end. Strangely I have this issue with `@unleash/proxy-client-react` v4 but not with v4.0.1 Cleaning all dependencies, doing fresh install and maybe rebooting your IDE can help. You're not using `@unleash/nextjs`, right? That one shouldn't require other SDKs as explicit dependencies

We are doing all the updates via dependabot and CI/CD there is no human involved. The issue is with 4.0.1.

**Comment by Tymek** [comment]
I'm releasing v4.0.1 now
