### ISSUE TITLE
jest.mock does not find the module anymore since 4.0.2

### ISSUE THREAD

**Issue by AdrienFromToulouse** [Unleash/proxy-client-react#142]
### Describe the bug

Hi,

Since the version 4.0.2 we have trouble mocking it i.e jest.mock('@unleash/proxy-client-react') is failing to find the module.

```Cannot find module '@unleash/proxy-client-react' from ...```

We are running the latest version of jest and other testing libraries and don't have any issues with other library that we mock such as `@auth0/auth0-react` for instance.
Tried `__esModule: true,` in the jest.mock option with no success.

Could be linked to an "issue" in the way the `package.json` defines the module? I am really not familiar with all the subtleties, but could it be linked to the "./dist/unleash-react.umd.js" i.e the fact that it is a `umd` module?

# context and version

npm version

```
{
  npm: '10.1.0',
  node: '20.8.0',
  acorn: '8.10.0',
  ada: '2.6.0',
  ares: '1.19.1',
  base64: '0.5.0',
  brotli: '1.0.9',
  cjs_module_lexer: '1.2.2',
  cldr: '43.1',
  icu: '73.2',
  llhttp: '8.1.1',
  modules: '115',
  napi: '9',
  nghttp2: '1.56.0',
  nghttp3: '0.7.0',
  ngtcp2: '0.8.1',
  openssl: '3.0.10+quic',
  simdutf: '3.2.17',
  tz: '2023c',
  undici: '5.25.2',
  unicode: '15.0',
  uv: '1.46.0',
  uvwasi: '0.0.18',
  v8: '11.3.244.8-node.16',
  zlib: '1.2.13.1-motley'
}
```

jest: `"jest": "^29.7.0"`
nextjs: "next": "13.5.4"

Cheers,

### Subscription type

Pro

### Hosting type

Hosted by Unleash

### SDK information (language and version)

"next": "13.5.4", "typescript": "^4.9.5",

**Comment by andreas-unleash** [comment]
Hi @AdrienFromToulouse  thanks for bringing this to our attention. I will ask the team to look into it.

**Comment by Tymek** [comment]
Thank you @AdrienFromToulouse for reporting this issue. `v4.0.3` should have that fixed.

```ts
import { jest } from "@jest/globals";
import { UnleashClient } from "@unleash/proxy-client-react";

jest.mock("@unleash/proxy-client-react", () => ({
  UnleashClient: "mockedValue",
}));

test("mock UnleashClient", () => {
  expect(UnleashClient).toBe("mockedValue");
});
```

**Comment by AdrienFromToulouse** [comment]
many thanks for your quick fix!

❤️
