### ISSUE TITLE
Flag errors are not cleared after the error is gone

### ISSUE THREAD

**Issue by kwasniew** [Unleash/proxy-client-react#150]
### Describe the bug

useFlagStatus returns flagsError when some error occurs e.g. client lost network connection. When everything goes back to normal the flagsError should be removed while currently it always remembers the last error.

### Subscription type

None

### Hosting type

None

**Comment by thomasheartman** [comment]
This has been in done for two weeks, but not closed. Closing now. Reopen if you need to.
