### ISSUE TITLE
Support for currentTime context (unleash-proxy-client-js@v3.3.1)

### ISSUE THREAD

**Issue by AdrienFromToulouse** [Unleash/proxy-client-react#157]
### Describe the feature request

Hi,

Following the recent release of https://github.com/Unleash/unleash-proxy-client-js/releases/tag/v3.3.1 for [currentTime](https://github.com/Unleash/unleash-proxy-client-js/pull/195) 

Will it be supported anytime soon? I can see it is still using a beta version https://github.com/Unleash/proxy-client-react/blob/main/package.json#L53

Cheers,

**Comment by sjaanus** [comment]
@AdrienFromToulouse I will verify this, but should be able to upgrade in following hours.

**Comment by sjaanus** [comment]
Released as https://github.com/Unleash/proxy-client-react/releases/tag/v4.1.2
