### ISSUE TITLE
Unleash: unable to fetch feature toggles TypeError: Cannot read properties of undefined (reading 'find')

### ISSUE THREAD

**Issue by mavericardo** [Unleash/proxy-client-react#160]
### Describe the bug

I'm trying to check my feature toggle using the hook `useFlag` from `@unleash/proxy-client-react` But I'm getting the following error within library:

<img width="756" alt="Screenshot 2024-02-21 at 10 48 58" src="https://github.com/Unleash/proxy-client-react/assets/27781419/23c714bd-aeab-41c4-9498-5a9eaf78387a">

### Steps to reproduce the bug

1. Makes the simple configuration 
2. Try uses the useFlag() hook

### Expected behavior

Returns my feature flag information.

### Unleash version

"@unleash/proxy-client-react": "^3.6.0" - "unleash-proxy-client": "^2.5.0"

### Subscription type

None

### Hosting type

None

### SDK information (language and version)

React

**Comment by FredrikOseberg** [comment]
@mavericardo Thanks for the report. Could you provide a reproducable example here? I suspect there may be a configuration issue, even though the error message looks scary. I'd like to get to the bottom of this, so any information you could give me would be appreciated!

**Comment by FredrikOseberg** [comment]
Closing this for now. Feel free to re-open with new information.
