### ISSUE TITLE
Flags status is incorrect when an already started unleash client is passed to flag provider

### ISSUE THREAD

**Issue by cemreyavuz** [Unleash/proxy-client-react#168]
### Describe the bug

I have a case that I want to pass an already started unleash client to the unleash flag provider. When I do that, `flagsReady` (returned from `useFlagsStatus` hook) returns `false` even though the client is started and ready.

Here is a reproducible example: https://stackblitz.com/edit/vitejs-vite-elpthg?file=src%2FApp.tsx.

As far as I see, this behaviour is this way due to calling the `readyCallback` only when we get the `ready` event from the client. In my case, this event is never sent since the client is already ready before the flag provider component is initialized:
https://github.com/Unleash/proxy-client-react/blob/4656873b1ddb699f6268fb0b13c719e451d3a84b/src/FlagProvider.tsx#L77

I wonder if this is intentional and whether the case I mentioned is an intended way of using unleash client or not. Happy to contribute if it is decided to be an actual bug - but I might still need some pointers.

### SDK information (language and version)

`unleash-proxy-client@3.4.0` and `@unleash/proxy-client-react@4.2.3`

**Comment by Tymek** [comment]
O, that looks like a legitimate issue for sure.
