### ISSUE TITLE
Can we support turning on/off metrics?

### ISSUE THREAD

**Issue by smksnutmeg** [Unleash/proxy-client-react#2]
We have built a proxy for unleash and we scrape metrics differently.
`https://API_HOST/feature_flags/client/metrics` will return a 404 for us.
Can we make it optional to fire metrics?

**Comment by ivarconr** [comment]
Yes makes sense. Underlaying JS SDK already have an option for that. Up for a PR?

**Comment by smksnutmeg** [comment]
Yeah sure will prep one :)

**Comment by ivarconr** [comment]
solved via #7
