### ISSUE TITLE
getAllToggles not exposed

### ISSUE THREAD

**Issue by KeisBabis** [Unleash/proxy-client-react#28]
It looks like the proxy-client-react does not implement getAllToggles method available in the unleash-proxy-client. Is this intentional or are there any plans to have that in the future?

**Comment by FredrikOseberg** [comment]
> It looks like the proxy-client-react does not implement getAllToggles method available in the unleash-proxy-client. Is this intentional or are there any plans to have that in the future?

As of 1.0.2 the react proxy client re-exports the UnleashClient from the unleash-proxy-client library and accepts an unleashClient parameter in the flagProvider. This means that you can use the client directly to call the getAllToggles method. Does that solve your issue?
