### ISSUE TITLE
this.toggles.find is not a function

### ISSUE THREAD

**Issue by ChrisLFieldsII** [Unleash/proxy-client-react#34]
I am using this pkg in a react-native app.

I have configured the `storageProvider` exactly as mentioned in the README to use `AsyncStorage`

I randomly notice an error in development. I took a screenshot of the error [here](https://drive.google.com/file/d/1ykBDvzADD2_sxeZwceL-D76rKt_zfIL1/view?usp=sharing)

It seems that sometimes, `this.toggles` is a `string` when an `array` is expected.

I verified this logging through `node_modules/@unleash/proxy-client-react/index.js`. A screenshot of that is [here](https://drive.google.com/file/d/1fu8CwljgGV9nsNRPLN8h9FHmxBTINyDo/view?usp=sharing)

Previously when this bug occurred in development, the developers would uninstall/reinstall.

I confirmed that clearing `AsyncStorage` helps to resolve this bug without a uninstall/reinstall.

The company I work for is releasing our app to the wild next week and the fear is that this bug sneaks into production causing users to crash on app open.

**Comment by ivarconr** [comment]
Hi, thanks for reaching out!

I think the example must be improved a bit to also do the JSON parse on get. 

```js
const config = {
  storageProvider: {
    save: (name, data) => AsyncStorage.setItem(name, JSON.stringify(data)),
    get: async (name) => {
         const data = await AsyncStorage.getItem(name);
         return data ? JSON.parse(data) : undefined;
    }
  },
};
```

**Comment by ChrisLFieldsII** [comment]
Hey @ivarconr,

Yes! This sounds like the fix. 

Thanks for your help on this matter.

I am closing this issue.
