### ISSUE TITLE
handle HMR gracefully

### ISSUE THREAD

**Issue by pvinis** [Unleash/proxy-client-react#37]
when using this library, when HMR reloads, I see double requests on the network tab. and when it reloads another time, I see triple requests.

This should not be happening.

**Comment by FredrikOseberg** [comment]
> when using this library, when HMR reloads, I see double requests on the network tab. and when it reloads another time, I see triple requests.
> 
> This should not be happening.

@pvinis As far as I know that is how HMR works. See this theKasheys answer in this [issue](https://github.com/gaearon/react-hot-loader/issues/930). Or if you know something I don't, please enlighten me and I'll be happy to have a discussion on this.
