### ISSUE TITLE
Usage with next.js

### ISSUE THREAD

**Issue by marjak93** [Unleash/proxy-client-react#40]
Hello, apologies if this is the wrong place to post this.

We're in the process of integrating unleash with our next.js applications. We've set up proxies externally and gotten up and running. We've solved some issues with specifically `fetch` and `localStorage` not being available during SSR by extending the unleash provider with our own, like this:

```tsx
// Provider.tsx

const UnleashProvider: typeof FlagProvider = ({ config = {}, children }) => {
  // To prevent from throwing during SSR, pass a dummy storage provider
  const storageProvider = isNode
    ? new DummyStorageProvider()
    : window.localStorage;

  // Similarly, pass a dummy fetch provider
  const fetchProvider = isNode ? fetch : undefined;

  return (
    <FlagProvider
      config={{
        storageProvider,
        fetch: fetchProvider,
        url: process.env["UNLEASH_URL"],
        clientKey: process.env["UNLEASH_CLIENT_KEY"],
        refreshInterval: 15,
        appName: process.env["APP_NAME"],
        environment: process.env["APP_ENV"],
        ...config,
      }}
    >
      {children}
    </FlagProvider>
  );
};
```

```ts
// DummyProvider.ts

export class DummyStorageProvider {
  async save() {
    return;
  }

  async get() {
    return "";
  }
}
```

However, this feels very hacky and I'm wondering if the unleash team has any advice to give for integrating with next.js?

**Comment by FredrikOseberg** [comment]
> Hello, apologies if this is the wrong place to post this.
> 
> We're in the process of integrating unleash with our next.js applications. We've set up proxies externally and gotten up and running. We've solved some issues with specifically `fetch` and `localStorage` not being available during SSR by extending the unleash provider with our own, like this:
> 
> ```tsx
> // Provider.tsx
> 
> const UnleashProvider: typeof FlagProvider = ({ config = {}, children }) => {
>   // To prevent from throwing during SSR, pass a dummy storage provider
>   const storageProvider = isNode
>     ? new DummyStorageProvider()
>     : window.localStorage;
> 
>   // Similarly, pass a dummy fetch provider
>   const fetchProvider = isNode ? fetch : undefined;
> 
>   return (
>     <FlagProvider
>       config={{
>         storageProvider,
>         fetch: fetchProvider,
>         url: process.env["UNLEASH_URL"],
>         clientKey: process.env["UNLEASH_CLIENT_KEY"],
>         refreshInterval: 15,
>         appName: process.env["APP_NAME"],
>         environment: process.env["APP_ENV"],
>         ...config,
>       }}
>     >
>       {children}
>     </FlagProvider>
>   );
> };
> ```
> 
> ```ts
> // DummyProvider.ts
> 
> export class DummyStorageProvider {
>   async save() {
>     return;
>   }
> 
>   async get() {
>     return "";
>   }
> }
> ```
> 
> However, this feels very hacky and I'm wondering if the unleash team has any advice to give for integrating with next.js?

@marjak93 We do have some recommendations. Are you looking to prefetch the feature toggles on the server side? Example getServerSideProps function (downside being that you have to wait for the API call): 

```
export async function getServerSideProps() {
  // Set up unleash to fetch only once in order to not create 
  // bindings for every request which will cause a memory leak
  const unleash = new UnleashClient({
    ...config,
    fetch,
    storageProvider: new InMemoryStorageProvider(),
    disableMetrics: true,
    disableRefresh: true 
  });

  // optinally update context
  unleash.updateContext({ userId: '123' });

  // await start to make sure the toggles have been fetched
  await unleash.start();

  // get all toggles
  const toggles = unleash.getAllToggles();


  return {
    props: {
      toggles,
    },
  };
}
```

For the FlagProvider you can follow the same suit and use the exported InMemoryStorageProvider and provide an alternative fetch implementation based on the environment. Here's an example passing in an initialised client with prefetched toggles: 

```
const config = {
  url: 'https://app.unleash-hosted.com/demo/proxy',
  clientKey: 'proxy-123',
  appName: 'ssr',
  projectName: 'default',
  refreshInterval: 1000,
  environment: 'dev',
};

function MyApp({ Component, pageProps }) {
  const ssrOption = typeof window !== "undefined"
    ? {}
    : { fetch: fetch, storageProvider: new InMemoryStorageProvider() };
    
  const client = new UnleashClient({
    ...config,
    ...ssrOption,
    bootstrap: pageProps.toggles,
  });
//

  return (
    <FlagProvider unleashClient={client}>
      <Component {...pageProps} />
    </FlagProvider>
  );
}
```

Hope that helps

**Comment by marjak93** [comment]
Thank you! We don't plan to prefetch toggles server-side yet. But maybe in the future?

Your suggestion for passing `InMemoryStorage` to the `FlagProvider` worked wonders!

Thank you for your help 👍
