### ISSUE TITLE
Sourcemap warnings from webpack 5 (via CRA 5)

### ISSUE THREAD

**Issue by jfairley** [Unleash/proxy-client-react#41]
I recently upgraded my app to `create-react-app` v5, which uses `webpack` v5 internally and the `source-map-loader`. The new `source-map-loader` is spewing warnings about the sourcemaps included in `unleash-proxy-client`.

More specifically, what it's unhappy about is that the sourcemaps reference the source files, but those source files are not included in the bundle.

Currently there is no way to hide these warnings and the React recommendation is to reach out to library maintainers. There is an [open issue](https://github.com/facebook/create-react-app/issues/11924) discussing this.

As I understand it, the two options here are:

1. remove sourcemaps from the distributed bundle
2. distribute the typescript source

I'll leave that decision up to y'all, or I'm happy to work up a PR if you'd like.

Thanks!

---

Warning output:

![Screen Shot 2022-03-02 at 10 34 02 AM](https://user-images.githubusercontent.com/992483/156417595-5461ee8f-c93e-49bb-8cb3-e234bd13ee1a.png)

Sample sourcemap content:

![Screen Shot 2022-03-02 at 10 41 39 AM](https://user-images.githubusercontent.com/992483/156418038-706659a4-42bc-4b56-8c03-6b25b518438d.png)

**Comment by FredrikOseberg** [comment]
@jfairley Happy to receive a PR. Removing the sourcemaps from the distributed bundle seems like the most efficient way to go here.
