### ISSUE TITLE
Conditionally render react <Route> element with useFlag

### ISSUE THREAD

**Issue by jdelucaa** [Unleash/proxy-client-react#43]
I am trying to use `useFlag` to conditionally render a react `<Route>` element, and I have the route configured to go to a `Not Found` page when the route doesn't match any defined `<Route>`, so while the flag status check is pending, the `Not Found` component appears on the screen for an instant and then as soon as the flag is evaluated the correct `<Route>` element is rendered.

My AppRouter:

```
const AppRouter: FunctionComponent = () => {
  const isEnabled = useFlag('my_flag');

  return (
    <BrowserRouter>
      <Routes>
        <Route path="/app/logging" element={<LoggingApp />} />
        { isEnabled && <Route path="/app/reporting" element={<ReportingApp profileName="xxx" />} /> }
        <Route
          path="*"
          element={
            <AppTheme>
              <ErrorPage errorCode={'404'} />
            </AppTheme>
          }
        />
      </Routes>
    </BrowserRouter>
  );
};

export default AppRouter;
```

Is there a way to know the flags are ready? The `useFlag` hook only exports the `enabled` status and the `useUnleashContext` only exports the `updateContext` function, so I cannot really know what is going on in the client.

Any ideas?

**Comment by thomasheartman** [comment]
Hey! 👋🏼 

Great question! And yes, if what you want is to know that the flags are ready, you can use the `useFlagStatus` hook, which returns an object with a `flagsReady` property 😄 

You can check out the ["Defer rendering until flags are fetched" section of the readme](https://github.com/Unleash/proxy-client-react#defer-rendering-until-flags-fetched) for a more detailed usage example. 

Does that provide you with what you were looking for? ☺️

**Comment by jdelucaa** [comment]
Oh, I totally missed that part in the documentation, my bad! Let me try it...

**Comment by jdelucaa** [comment]
> Hey! 👋🏼
> 
> Great question! And yes, if what you want is to know that the flags are ready, you can use the `useFlagStatus` hook, which returns an object with a `flagsReady` property 😄
> 
> You can check out the ["Defer rendering until flags are fetched" section of the readme](https://github.com/Unleash/proxy-client-react#defer-rendering-until-flags-fetched) for a more detailed usage example.
> 
> Does that provide you with what you were looking for? ☺️

Oh, I totally missed that part in the documentation, my bad! Let me try it...

**Comment by jdelucaa** [comment]
That's what I was looking for, thanks! I am closing the issue now. ❤️
