### ISSUE TITLE
Please expose FlagContext in the exported package so it can be consumed directly.

### ISSUE THREAD

**Issue by EdwardDrapkin** [Unleash/proxy-client-react#46]
There is currently no way to consume the FlagContext.  Even `useUnleashContext` only exposes one piece of it.

**Comment by FredrikOseberg** [comment]
> There is currently no way to consume the FlagContext. Even `useUnleashContext` only exposes one piece of it.

Hi Edward. I'm curious to know more about what your need is for exposing the FlagContex. Are you planning to build your own FlagProvider? The `useUnleashContext` is different from the react context in that it exposed a method that you can use to update the values that you communicate to the proxy. The rest of the FlagProvider methods are exposed through single hooks like `useFlag` or `useVariant`.

**Comment by EdwardDrapkin** [comment]
I wound up creating my own client instance, passing that to the context, and using that instead.  It doesn't feel great having to use both the proxy client and the react client, but it gets the job done so I was able to be unblocked.

Basically we have a flow where a user logins in, and then the login returns information we use for an activation strategy, and we need the data to be available in the `handleLogin` callback to determine what to do post-login.  So `handleLogin` hits the API, updates the context, but can't see the flag change until the next re-render cycle unless it queries the client directly.  

The way this SDK is setup, you can't see flag changes until a render cycle has completed so in cases where the context needs to be updated and _immediately_ responded to (like, on the very next line of code) require direct interaction with the client.  If the `useUnleashContext` exposes the entire context,  we could pull `isEnabled` out of the context rather than need to keep track of our own client.

Right now:

```
import unleashClient from 'unleashClient.ts';

function LoginComponent() {
  const updateContext = useUnleashContext();
  
  /* ... */
  
  handleLogin = async () => {
    /* ... */
    await updateContext(dataFromLoginResponseGoesHere);
    
    const enabled = unleashClient.isEnabled('feature-goes-here');
    if(enabled) {
      navTo(onePage);
    } else {
      navTo(anotherPage);
    }
    /* ... */
  }
}
```

If we could just import `isEnabled` from the same place we import `updateContext`, we wouldn't have to keep track of the unleash client ourselves which feels suboptimal when all we do with it is instantiate it with the exact options we'd otherwise pass to the provider, and then pass it to the provider instead.

**Comment by FredrikOseberg** [comment]
> I wound up creating my own client instance, passing that to the context, and using that instead. It doesn't feel great having to use both the proxy client and the react client, but it gets the job done so I was able to be unblocked.
> 
> Basically we have a flow where a user logins in, and then the login returns information we use for an activation strategy, and we need the data to be available in the `handleLogin` callback to determine what to do post-login. So `handleLogin` hits the API, updates the context, but can't see the flag change until the next re-render cycle unless it queries the client directly.
> 
> The way this SDK is setup, you can't see flag changes until a render cycle has completed so in cases where the context needs to be updated and _immediately_ responded to (like, on the very next line of code) require direct interaction with the client. If the `useUnleashContext` exposes the entire context, we could pull `isEnabled` out of the context rather than need to keep track of our own client.
> 
> Right now:
> 
> ```
> import unleashClient from 'unleashClient.ts';
> 
> function LoginComponent() {
>   const updateContext = useUnleashContext();
>   
>   /* ... */
>   
>   handleLogin = async () => {
>     /* ... */
>     await updateContext(dataFromLoginResponseGoesHere);
>     
>     const enabled = unleashClient.isEnabled('feature-goes-here');
>     if(enabled) {
>       navTo(onePage);
>     } else {
>       navTo(anotherPage);
>     }
>     /* ... */
>   }
> }
> ```
> 
> If we could just import `isEnabled` from the same place we import `updateContext`, we wouldn't have to keep track of the unleash client ourselves which feels suboptimal when all we do with it is instantiate it with the exact options we'd otherwise pass to the provider, and then pass it to the provider instead. Or, alternatively, which requires no breaking changes, if FlagContext is exported from the package, we can `useContext(FlagContext)` instead. That option would cover this edge case, as well as any other future edge-case.
> 
> I'd be happy to open the PR but I figured the change was trivial enough that the real concern was whether or not you'd accept the change.

@EdwardDrapkin 

Yeah, that makes sense. While I can't see anything wrong with explicitly exposing the context, something like a `useClient` hook might be better, and give us more flexibility on what to expose in the future. It might be that at a later point we'll want to use something internally through the context, that we don't want to expose publicly. 

I would be happy to receive a PR creating a useClient hook exposing the client, currently I'm on my honeymoon but I'll raise this internally once I get back.
