### ISSUE TITLE
Use with next.js / SSR

### ISSUE THREAD

**Issue by jebax** [Unleash/proxy-client-react#50]
Hi there,

In my next.js app, I currently use `unleash-client` in my server middleware and a custom implementation of `unleash-proxy-client` in my components. I pass down the server-side flags and use them as initial state, then initialize the proxy client in a `useEffect` and override the flags. This allows me to use feature flags during SSR, then continue checking them during CSRs.

I'd like to switch over to `proxy-client-react`, but I've run into a problem during SSR. The `FlagsProvider` always tries to initialize a client even if `window` isn't available, which results in errors while rendering. I know that I can initialize an `UnleashClient` in a `useEffect`, then prevent rendering `FlagsProvider` until the client has been initialized. But this would mean basically all of my app (anything rendered inside `FlagsProvider`) wouldn't be rendered during SSR, which results in a huge performance hit.

Ideally, `FlagsProvider` would also initialize the client in a `useEffect` to allow it to be rendered during SSR - has this been considered? React apps using SSR in production are extremely common these days, so I would've thought this is a pretty common use case. 

Alternatively, is there any other way you could recommend to get around this problem?

Thanks in advance!

**Comment by jebax** [comment]
that looks great, thanks! i'll keep an eye out for the next release.

**Comment by thomasheartman** [comment]
Perfect! I'm glad I could be of help 😄  I'll close this issue for now, then. Please don't hesitate to open another issue if you come across anything else!

**Comment by thomasheartman** [comment]
Just a little update here: the new (major) version is due out very soon now. But if you need something right away, there is a [beta release](https://www.npmjs.com/package/@unleash/proxy-client-react/v/1.1.0-beta.0) out already 💁🏼

**Comment by lapa182** [comment]
@thomasheartman Could you point out what's the version we need to install to fix this? I installed `2.0.0` and I'm still having the same issue :(.

**Comment by thomasheartman** [comment]
Hi, @lapa182 ! 👋🏼  It should be in v2.0.0. Can you tell me what the issue you're having is? Do the new FlagProvider options not work or is there something else?

**Comment by lapa182** [comment]
@thomasheartman Sorry for not replying early, it wasn't using 2.0.0, had a blip with the lock file. 🤦

**Comment by thomasheartman** [comment]
@lapa182 No worries; I'm glad you got it working! 😄

**Comment by elisechant** [comment]
Just following this thread. It's not clear to me here how [this code sample](https://github.com/Unleash/proxy-client-react/issues/50#issuecomment-1096487959) resolves the SSR compat issue. Can you explain?

**Comment by thomasheartman** [comment]
@elisechant Thanks for the input 😄 You're right in that it doesn't solve all SSR issues, but (at least if I understood everything correctly), it _does_ address the specific issue mentioned in the OP. That said, the comment you linked is a more thorough explanation of everything.

Putting it in the readme would be helpful, indeed! Part of the reason why we haven't done that yet, is that we don't have a complete story for SSR yet, and we wanted to get that down before we document it properly. However, I think you're right in that it would be useful to put what we have there, even if it's rough. I'll see what I can do 🙋🏼
