### ISSUE TITLE
Bundled for Target `node`

### ISSUE THREAD

**Issue by christian98** [Unleash/proxy-client-react#53]
### Describe the bug

When i try to build my react app (using `react-scripts@5.0.1`) i get the following error:

```
Failed to compile.

Module not found: Error: Can't resolve 'crypto' in '/***/node_modules/@unleash/proxy-client-react/dist'
```
(Complete logs down below)

### Steps to reproduce the bug

1. Create a new project with CRA and `react-scripts@5` (Using webpack v5 is important here)
2. Install this package (v2)
3. Try building the react project

### Expected behavior

No error ;)

### Logs, error output, etc.

```bash
Failed to compile.

Module not found: Error: Can't resolve 'crypto' in '/***/node_modules/@unleash/proxy-client-react/dist'
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "crypto": require.resolve("crypto-browserify") }'
        - install 'crypto-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "crypto": false }
```

### Additional context

I think the specific problem is that this library is built with target `node` in webpack.config.js . While experimenting i solved the problem by switching to target `web` (still don't completly know if this is the correct one; https://webpack.js.org/configuration/target/).
As of webpack v5 there are no polyfills for the node specific implementations (as the error message states). Because your webpack config targets `node` the bundler takes the wrong files from the package `uuid` (a dependency of `unleash-proxy-client-js`). Resulting in code targeting the wrong environment/platform.

IMO it would be even better to not bundle the dependencies of this lib into the package. This way my webpack installation could load the appropriate version of the `uuid` package. No matter what your webpack config is targeting.
Apart from that you would not need to publish new versions of this package if the proxy-client receives patch or minor updates. NPM could easily install the proxy-client version specified by this projects version constraints.

### SDK information (language and version)

2.0.0

**Comment by FredrikOseberg** [comment]
Thanks! Looks like this is due to webpack upgrading their major version causing breaking changes in how nodejs deps were previously handled. I will take your comments into considerations and find out how we will tackle this.

**Comment by christian98** [comment]
Alright, thanks.

**Comment by FredrikOseberg** [comment]
> Alright, thanks.

If you have a solution ready that will solve this issue and work with server side rendering solutions, feel free to submit a PR.

**Comment by FredrikOseberg** [comment]
@christian98 Can you update to `3.0.0-beta.0`? It should solve the issue.

**Comment by christian98** [comment]
Looks promising. I will try tomorrow. Thanks in advance.

**Comment by christian98** [comment]
Nice! I think this does the trick. It seems to work now.

The only things i get are these Sourcemap warnings from `unleash-proxy-client`. But these should be fixed with the next release of that package, no?

```
WARNING in ./node_modules/unleash-proxy-client/build/events-handler.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/***/node_modules/unleash-proxy-client/src/events-handler.ts' file: Error: ENOENT: no such file or directory, open '/***/node_modules/unleash-proxy-client/src/events-handler.ts'

WARNING in ./node_modules/unleash-proxy-client/build/index.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/***/node_modules/unleash-proxy-client/src/index.ts' file: Error: ENOENT: no such file or directory, open '/***/node_modules/unleash-proxy-client/src/index.ts'

WARNING in ./node_modules/unleash-proxy-client/build/metrics.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/***/node_modules/unleash-proxy-client/src/metrics.ts' file: Error: ENOENT: no such file or directory, open '/***/node_modules/unleash-proxy-client/src/metrics.ts'

WARNING in ./node_modules/unleash-proxy-client/build/storage-provider-inmemory.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/***/node_modules/unleash-proxy-client/src/storage-provider-inmemory.ts' file: Error: ENOENT: no such file or directory, open '/***node_modules/unleash-proxy-client/src/storage-provider-inmemory.ts'

WARNING in ./node_modules/unleash-proxy-client/build/storage-provider-local.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/***/node_modules/unleash-proxy-client/src/storage-provider-local.ts' file: Error: ENOENT: no such file or directory, open '/***/node_modules/unleash-proxy-client/src/storage-provider-local.ts'

WARNING in ./node_modules/unleash-proxy-client/build/util.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/***/node_modules/unleash-proxy-client/src/util.ts' file: Error: ENOENT: no such file or directory, open '/***/node_modules/unleash-proxy-client/src/util.ts'

webpack compiled with 6 warnings
```

Apart from that everything seems to work smoothly. Thank you!

**Comment by FredrikOseberg** [comment]
> Nice! I think this does the trick. It seems to work now.
> 
> The only things i get are these Sourcemap warnings from `unleash-proxy-client`. But these should be fixed with the next release of that package, no?
> 
> ```
> WARNING in ./node_modules/unleash-proxy-client/build/events-handler.js
> Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
> Failed to parse source map from '/***/node_modules/unleash-proxy-client/src/events-handler.ts' file: Error: ENOENT: no such file or directory, open '/***/node_modules/unleash-proxy-client/src/events-handler.ts'
> 
> WARNING in ./node_modules/unleash-proxy-client/build/index.js
> Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
> Failed to parse source map from '/***/node_modules/unleash-proxy-client/src/index.ts' file: Error: ENOENT: no such file or directory, open '/***/node_modules/unleash-proxy-client/src/index.ts'
> 
> WARNING in ./node_modules/unleash-proxy-client/build/metrics.js
> Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
> Failed to parse source map from '/***/node_modules/unleash-proxy-client/src/metrics.ts' file: Error: ENOENT: no such file or directory, open '/***/node_modules/unleash-proxy-client/src/metrics.ts'
> 
> WARNING in ./node_modules/unleash-proxy-client/build/storage-provider-inmemory.js
> Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
> Failed to parse source map from '/***/node_modules/unleash-proxy-client/src/storage-provider-inmemory.ts' file: Error: ENOENT: no such file or directory, open '/***node_modules/unleash-proxy-client/src/storage-provider-inmemory.ts'
> 
> WARNING in ./node_modules/unleash-proxy-client/build/storage-provider-local.js
> Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
> Failed to parse source map from '/***/node_modules/unleash-proxy-client/src/storage-provider-local.ts' file: Error: ENOENT: no such file or directory, open '/***/node_modules/unleash-proxy-client/src/storage-provider-local.ts'
> 
> WARNING in ./node_modules/unleash-proxy-client/build/util.js
> Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
> Failed to parse source map from '/***/node_modules/unleash-proxy-client/src/util.ts' file: Error: ENOENT: no such file or directory, open '/***/node_modules/unleash-proxy-client/src/util.ts'
> 
> webpack compiled with 6 warnings
> ```
> 
> Apart from that everything seems to work smoothly. Thank you!

Nice. These webpack warnings will be fixed shortly, I added a fix yesterday in the base client [here](https://github.com/Unleash/unleash-proxy-client-js/pull/82)

I will update this client with these changes and release the official version shortly.

**Comment by FredrikOseberg** [comment]
@christian98 3.0.0 is released.
