### ISSUE TITLE
Support for React 18

### ISSUE THREAD

**Issue by aalemayhu** [Unleash/proxy-client-react#60]
### Describe the feature request

We want to use Unleash in a project which uses React 18 and are seeing the following messages in the console. Is there any plans to upgrade to latest React version?
```
react-dom.development.js:86 Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot
[...]
react-dom.development.js:86 Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot
```

Thanks.

**Comment by olav** [comment]
Hello, thanks for the report!

This library does not call `ReactDOM.render` itself, so those warnings would have to be fixed in the application's code.

We should update the example code in `README.md` to use `createRoot`.
