### ISSUE TITLE
Yarn berry: pnp incompatibility 

### ISSUE THREAD

**Issue by harris-jacob** [Unleash/proxy-client-react#66]
### Describe the bug

We are getting the following error when trying to migrate to yarn pnp (which no longer supports implicit dependencies like flat node_modules does):

```
ERROR in ../../../.yarn/cache/@unleash-proxy-client-react-npm-1.0.4-06a181db73-957ee588a0.zip/node_modules/@unleash/proxy-client-react/dist/index.js 1:20854-20870
Module not found: Error: Can’t resolve ‘react’ in ‘User/dev/project/.yarn/cache/@unleash-proxy-client-react-npm-1.0.4-06a181db73-957ee588a0.zip/node_modules/@unleash/proxy-client-react/dist’
```

### Steps to reproduce the bug

1. start a yarn pnp project
2. add this package

### Expected behavior

I think this issue is just because react & react-dom are listed as`devDependencies` instead of a `peerDependencies`

**Comment by FredrikOseberg** [comment]
Hi. Thanks for reporting this, we'll look into this early next week.

**Comment by Tymek** [comment]
Related issue: https://github.com/Unleash/unleash/pull/1584

**Comment by Tymek** [comment]
@harris-jacob I couldn't reproduce the issue in blank Yarn Berry project with PnP enabled. Can you share more details? What is you order of operations? Seems like you use `v1.0.4`, did you try update to the latest version?

**Comment by harris-jacob** [comment]
Yes you're right i've tried reproducing in a smaller repo but am unable to. We have a fairly large monorepo setup so the issue could be coming from elsewhere (I just assumed from the error message it was a missing peer dependency). We've actually given up attempting PnP now due to lots of similar errors. Will close this issue (out of curiosity, is there are reason you don't declare react as a peer dependency? )

**Comment by Tymek** [comment]
The fact that package managers handle it in a different way is a factor. We can reasonably expect that you add this package to a React project, not React to a project with this package. If there is any braking change that will limit compatibility of this package with new version of React, we will probably use `peerDependecy` to signal an issue, otherwise it doesn't provide much value.

**Comment by elisechant** [comment]
For others, this can be worked around in .yarnrc.yml [packageExtensions](https://yarnpkg.com/configuration/yarnrc/#packageExtensions):

.yarnrc.yml:

```
packageExtensions:
  "@unleash/proxy-client-react@^3.3.0":
    dependencies:
      react: ^18.1.0
```

Of course, adjust for the versions you are targeting.
