### ISSUE TITLE
`unleash-proxy-client` version constraint too tight

### ISSUE THREAD

**Issue by christian98** [Unleash/proxy-client-react#69]
### Describe the feature request

Currently, we cannot update `unleash-proxy-client` to v2.0.2 because the peerDependency in this package only allows v2.0.1 and nothing else:
```json
"peerDependencies": {
    "unleash-proxy-client": "2.0.1"
  }
```

Would it be possible to support a version constraint for the whole major of v2 like:
```json
"peerDependencies": {
    "unleash-proxy-client": "^2.0.1"
  }
```

### Background

We try to keep up with most of the new versions released by third-party dependencies we are using. But currently, our automated upgrade process (we are using renovate by the way ;) ) is not able to upgrade because of this output:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @unleash/proxy-client-react@3.1.0
npm ERR! Found: unleash-proxy-client@2.0.2
npm ERR! node_modules/unleash-proxy-client
npm ERR!   unleash-proxy-client@"2.0.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer unleash-proxy-client@"2.0.1" from @unleash/proxy-client-react@3.1.0
npm ERR! node_modules/@unleash/proxy-client-react
npm ERR!   @unleash/proxy-client-react@"3.1.0" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: unleash-proxy-client@2.0.1
npm ERR! node_modules/unleash-proxy-client
npm ERR!   peer unleash-proxy-client@"2.0.1" from @unleash/proxy-client-react@3.1.0
npm ERR!   node_modules/@unleash/proxy-client-react
npm ERR!     @unleash/proxy-client-react@"3.1.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
```

### Solution suggestions

As described previously it would be helpful if we could get a widen version constraint for `unleash-proxy-client`. Otherwise, you would have to release a new version with every release of `unleash-proxy-client`.

**Comment by nunogois** [comment]
Hi @christian98 - Many thanks for bringing this to our attention.
https://github.com/Unleash/proxy-client-react/pull/70 should address this from now on.

**Comment by christian98** [comment]
Nice! That was quick. Thank you very much!
