### ISSUE TITLE
Unleash: unable to fetch feature toggles TypeError: q.randomFillSync is not a function

### ISSUE THREAD

**Issue by melloware** [Unleash/proxy-client-react#76]
### Describe the bug

**React 18.2.0**
**unleash/proxy-client-react: 3.3.0**

I have a very simple App using Create React App and I have following your instructions exactly from here: https://docs.getunleash.io/sdks/proxy-react

AS soon I hit my page I can see the error in the console and my page does not render.

```ts
const AccountsPage = () => {
	const { flagsReady } = useFlagsStatus();
	const enabled = useFlag('account-management');
	const msgFeatureFlag = useRef<Messages>(null);

	useEffect(() => {
		if (enabled) {
			msgFeatureFlag.current?.replace({ severity: 'success', detail: 'Account Management feature flag is enabled!', sticky: true });
		} else {
			msgFeatureFlag.current?.replace({ severity: 'warn', detail: 'Account Management feature flag is disabled!', sticky: true });
		}
	}, [flagsReady, enabled]);

	return (
		<Messages ref={msgFeatureFlag} />
	);
};
```

### Steps to reproduce the bug

Simply run a Create React App app and try and use any feature flag I can see it hit the Unleash server and gather metrics from the proxy but the client is throwing this error `q.randomFillSync is not a function`

![image](https://user-images.githubusercontent.com/4399574/191080708-10613250-46ab-46ba-bb85-8af64f1529c6.png)

### Expected behavior

The feature flag would work.

### Logs, error output, etc.

```bash
main.min.js:1 Unleash: unable to fetch feature toggles TypeError: q.randomFillSync is not a function
    at g (main.min.js:1:1)
    at j (main.min.js:1:1)
    at a.generateEventId (main.min.js:1:1)
    at a.createBaseEvent (main.min.js:1:1)
    at a.createImpressionEvent (main.min.js:1:1)
    at f.isEnabled (main.min.js:1:1)
    at p (index.browser.js:1:1)
    at index.browser.js:1:1
    at f.emit (main.min.js:1:1)
    at f.<anonymous> (main.min.js:1:1)
```

### Screenshots

![image](https://user-images.githubusercontent.com/4399574/191080212-1ee34a07-dc5e-4eed-b413-887839d12a72.png)

### Unleash version

```
"@unleash/proxy-client-react": "^3.3.0"
"unleash-proxy-client": "^2.2.0"
```

### Subscription type

Open source

### Hosting type

Self-hosted

**Comment by melloware** [comment]
The error only occurs when Enable Impression Data is enabled.

![image](https://user-images.githubusercontent.com/4399574/191093208-2ee96588-1086-4471-bfce-640903f2d7b5.png)

**Comment by thomasheartman** [comment]
Hey, @melloware! Thanks for reporting this 🙌🏼  I'll make sure we look into this! But from what you're saying, it appears that impression data is a likely culprit. Let us get back to you later today or on monday?

**Comment by melloware** [comment]
Thank you!  Yes it seems similar to an older ticket I found related to impression data so when I turned it off it started working so I assumed its similar to that old issue.

**Comment by thomasheartman** [comment]
Hey, again! 👋🏼 

I tried reproducing this now, but wasn't able to. I created a new CRA, added the proxy client etc and the react client, but didn't have any issues. I didn't create a ref because that apparently doesn't work with function components, but I had no other issues, with or without impression data. What version of Unleash and the proxy are you using? 

Do you have any other bits of information or a reproducible repo I can use? 

Just to be clear: are you seeing the error in _your client application_ or in the _Unleash admin UI_? I can't seem to find any error in either, for what it's worth 🤷🏼

**Comment by melloware** [comment]
OK i just updated to proxy client 2.2.1 and now I can not reproduce this issue either.  Maybe it was this ticket that fixed this issue: https://github.com/Unleash/unleash-proxy-client-js/issues/111
