### ISSUE TITLE
useFlag breaks server side

### ISSUE THREAD

**Issue by damiangreen** [Unleash/proxy-client-react#78]
### Describe the bug

Our app is both SSR and client side rendered and as such we need to use both `@unleash/proxy-client-react`, as well as `unleash-client` `unleash-proxy-client`

`TypeError: Cannot read properties of null (reading 'isEnabled')`

To get this working we need to do something along these lines 
```
import { useReactiveVar } from '@apollo/client'
import { useFlag } from '@unleash/proxy-client-react'
import { variables } from 'core/variables'
import { UnleashFlagKey } from 'types/UnleashFlagKey'

const useUnleashFlag = (flag: UnleashFlagKey) => {
  const serverFlag = useReactiveVar(variables.unleashFeatures)[flag]
  const clientFlag = useFlag(flag)
  return serverFlag || clientFlag
}

export default useUnleashFlag
```

However on initial server render it throws  which would then mean we'd need to change this implement to have conditional hooks.

It would be preferable if it would return `undefined` rather than throwing

**Comment by FredrikOseberg** [comment]
> 

How have you set up the flag provider when using useFlag? The error message suggests that there is no running client defined. Are you using the useFlag function in a component that is outside the render tree of the flag provider?

**Comment by damiangreen** [comment]
I managed to get it working by using the notes in https://github.com/Unleash/proxy-client-react/issues/40#issuecomment-1048761755
So i'll close
