### ISSUE TITLE
Expose setContextField from client

### ISSUE THREAD

**Issue by nandoofz** [Unleash/proxy-client-react#89]
### Describe the feature request

In the `unleash-proxy-client-js` [documentation](https://github.com/Unleash/unleash-proxy-client-js#how-to-use-the-client-as-a-module) it is possible to update only one context property as seen in the image:
<img width="627" alt="image" src="https://user-images.githubusercontent.com/2110047/198351466-ad5fb487-939a-4d56-a30c-ad69734769a0.png">

Although it is possible using the `useUnleashClient`, it would be interesting to be able to do it in a simpler way without the need to use the `useUnleashClient`, having direct access to the `setContextField`.

### Background

I make use of several custom strategies, so I define several properties within the context. There are specific cases where I need to update some properties of the context, but the `updateContext` overwrites everything, erasing the other properties.

It is possible to do with `proxy-client-react` through `useUnleashClient` as in the example:
```js
import { useUnleashClient } from '@unleash/proxy-client-react'

const MyApp = ({ someIdFromMyCustomStrategy }) => {
  const unleashClient = useUnleashClient();
  unleashClient.setContextField('myCustomPropName', someIdFromMyCustomStrategy);

  return <MyComponent />;
}
```

Although the request triggered to the proxy has the parameter duplicated:
Withou using `setContextField`:
`https://unleash-proxy.../proxy?environment=development&appName=myApp&myCustomProp=customValue`

Using `setContextField`:
`https://unleash-proxy.../proxy?environment=development&appName=myApp&myCustomProp=customValue&properties%5BmyCustomProp%5D=newCustomValue`

### Solution suggestions

Using the `proxy-client-react` directly, could be something like:
```js
import { useUnleashContext } from '@unleash/proxy-client-react'

const MyApp = ({ someIdFromMyCustomStrategy }) => {
  const unleashContext = useUnleashContext();
  unleashContext.setContextField('myCustomPropName', someIdFromMyCustomStrategy);

  return <MyComponent />;
}
```

Or even like:
```js
import { useUnleashContext } from '@unleash/proxy-client-react'

const MyApp = ({ someIdFromMyCustomStrategy }) => {
  const unleashContext = useUnleashContext();
  unleashContext.setContextFields({
    myCustomProp: someIdFromMyCustomStrategy,
    otherCustomProp: otherValue,
  });

  return <MyComponent />;
}
```

**Comment by thomasheartman** [comment]
Hey, @nandoofz 🙋🏼 Thanks for opening the issue and for the suggestion. Overall, I think this sounds very sensible, and I quite like your last suggestion of using an object for setting multiple context fields at the same time 🙌🏼 

Considering this is already possible to do today, I don't think we can dedicate too much time to it right now, but if you'd be willing to provide a PR, we'd be happy to work with you on it? 😄 

Oh, and regarding this bit:

> Although the request triggered to the proxy has the parameter duplicated:
> Without using `setContextField`:
> `https://unleash-proxy.../proxy?environment=development&appName=myApp&myCustomProp=customValue`
>
> Using `setContextField`:
> `https://unleash-proxy.../proxy?environment=development&appName=myApp&myCustomProp=customValue&properties%5BmyCustomProp%5D=newCustomValue`

That seems strange, but not entirely unexpected, I think. Can you give me a little more context? 

For the first one, you say that it's without using `setContextField`: how **did** you set it, if not with `setContextField`? Did you provide it at startup?

For the second one: you've got two values, and I'm assuming only the second was set with `setContextField`. Was the first one set the same way as the value in the previous example?
