### ISSUE TITLE
Props of FlagProvider is not exported

### ISSUE THREAD

**Issue by yarinsa** [Unleash/proxy-client-react#91]
### Describe the bug

We want to have our own "FlagProvider" and we want to extend the original props, in case you guys add some properties to it, the interface will be up to date. The problem "IFlagProvider" is not exported.

### Unleash version

3.4.0

### Subscription type

Enterprise

### Hosting type

Hosted by Unleash

### SDK information (language and version)

proxy-client-react@3.4.0

**Comment by FredrikOseberg** [comment]
I don't see a reason why we shouldn't export that. Would you mind setting up a PR? Otherwise I'll see if I can get it into the next sprint. @yarinsa
