### ISSUE TITLE
Potential bug - React state update on a component that hasn't mounted yet

### ISSUE THREAD

**Issue by nmaties** [Unleash/proxy-client-react#97]
### Describe the bug

Hello there,

I am using proxy-client-react in a project along with Next.js and while navigating through the pages I am getting an error `React state update on a component that hasn't mounted yet`, as per below screenshot:
![Screenshot 2022-12-21 at 13 30 46](https://user-images.githubusercontent.com/16613184/208917072-df4f04b2-8330-41f6-a520-0a52cc669e7b.png)

I had a look into my code to see if I am not doing clean up properly in the useEffects that I have but I think that's not the case.

I think I should try to use your latest version anyways.

Is this something that I should expect while using unleash with next.js?
There is no full integration with Next.js at the moment?

Thanks!

### Screenshots

![Screenshot 2022-12-21 at 13 30 46](https://user-images.githubusercontent.com/16613184/208917433-a6cf25ed-4e25-41dc-bfe3-a22d739b9287.png)

### Unleash version

^1.0.4

### Subscription type

Enterprise

### Hosting type

Hosted by Unleash

**Comment by sjaanus** [comment]
Hi @nmaties, thank you for reporting this. We don't have full integration with NextJS at this moment, but it is supported with some workarounds.
We have not seen your exact issue, but maybe following issues are helpful to set everything up.

https://github.com/Unleash/proxy-client-react/issues/86
https://github.com/Unleash/proxy-client-react/issues/40

**Comment by nmaties** [comment]
Hi @sjaanus, thank you for your reply, I'll try to upgrade to the latest version + I'll follow the issues that you mentioned.
I assume that we can close this issue at the moment, if after upgrading I'll still encounter the same problem I'll create a new issue.
