### ISSUE TITLE
useFlagsStatus always returns false for flagsReady

### ISSUE THREAD

**Issue by matt2112** [Unleash/proxy-client-react#98]
### Describe the bug

Hello! We recently upgraded from 3.4.0 to 3.5.0, and noticed that for some reason our feature toggles aren't working when running locally. We have a wrapper hook with the following line:

```ts
const { flagsReady, flagsError } = useFlagsStatus()
```

Previously `flagsReady` would come back as `true` if everything is fine, but now it only seems to be `false`. It's not obvious to me why though, as the 3.5.0 release only appears to contain dependency upgrades. But if I downgrade to 3.4.0 and don't change anything else, it works fine as usual. I also tried the v3.5.0-beta.0 release and found the same issue.

Strangely, it _does_ seem to work fine in our staging deployment. But we've tried on two different machines and found the same thing.

### Subscription type

Open source

### Hosting type

Self-hosted

**Comment by pransh15** [comment]
Hi @matt2112 👋 

Thanks for sharing the bug. It is odd that is works on staging, and not otherwise. Since you were able to make it work on two different machines, can you share the steps to reproduce this?

**Comment by matt2112** [comment]
Hi @pransh15 👋  Steps are just:
- Insert `const { flagsReady } = useFlagsStatus()` anywhere and log `flagsReady`, always false.
- Stop dev server.
- Run `yarn add @unleash/proxy-client-react@3.4.0`. Change nothing else and restart dev server.
- Log `flagsReady`, always true.
- Stop dev server.
- Run `yarn add @unleash/proxy-client-react@3.5.0`. Change nothing else and restart dev server.
- Log `flagsReady`, back to always being false.

To clarify, I mean we've replicated the bug on two different machines. If it's relevant, this is with React 18.2.0 and Next 12.3.3.

**Comment by clouddra** [comment]
I can confirm this behavior as well. here is a simple reproduction

```tsx
export function TestFlags() {
  const { flagsReady, flagsError } = useFlagsStatus();

  if (!flagsReady) return <div>loading</div>;

  return <div>done</div>;
}

ReactDOM.createRoot(document.getElementById('root') as HTMLElement).render(
  <React.StrictMode>
      <FlagProvider config={config}>
        <TestFlags />
      </FlagProvider>
  </React.StrictMode>,
);
```

**Comment by pransh15** [comment]
Thanks for sharing, @matt2112 and @clouddra 👍 
Let me try and reproduce in some time and get back to you! 😄

**Comment by matt2112** [comment]
Thanks for fixing this @Tymek, much appreciated! Can confirm it now works as expected 🎉
